name: Test with VUnit

on:
  push:
  pull_request:

jobs:
  container-job:
    runs-on: self-hosted
    container: modelsim:latest
    steps:
  
    - uses: actions/checkout@v2
  
    - run: ./run.py -p $(nproc)
