name: Test with VUnit

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  run-tests:
    runs-on: self-hosted
    container: docker.io/library/modelsim:latest
    steps:
    
    - uses: actions/checkout@v2
  
    - run: ./run.py -p $(nproc)
