name: Test with VUnit

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  container-job:
    runs-on: self-hosted
    container: goldensniper/modelsim-docker
    steps:
  
    - uses: actions/checkout@v2
  
    - run: ./run.py -p $(nproc)
