name: Test with VUnit

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  run-tests:
    runs-on: self-hosted
    container: localhost:5000/modelsim:latest
    steps:
    
    - uses: actions/checkout@v1
  
    - run: pip3 install -r requirements.txt && PATH=/modelsim/modelsim_ase/bin/:$PATH ./run.py -p $(nproc)
