name: Run tests with tox
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: veryl-lang/setup-verilator@v1
      with:
        version: 5.028
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [verilator]
