name: Run tests with tox
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt update && sudo apt install verilator
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [verilator]
